name: Update Last Updated Timestamp

on:
  push:
    branches:
      - FirstRelease  # Trigger on push to the branch
  pull_request:
    branches:
      - FirstRelease  # Trigger on pull request to the branch

jobs:
  update-last-updated:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Update the "Last Updated" placeholder
      - name: Update Last Updated Timestamp
        run: |
          # Get the current date and time
          current_datetime=$(date '+%B %d, %Y, %I:%M %p')

          # Update the placeholder in e-index.html
          sed -i "s/<!-- LAST_UPDATED: {TIMESTAMP} -->/<!-- LAST_UPDATED: $current_datetime -->/" e-index.html

          # Update the placeholder in index.html.html
          #sed -i "s/<!-- LAST_UPDATED: {TIMESTAMP} -->/<!-- LAST_UPDATED: $current_datetime -->/" index.html

          # Update the placeholder in all .html files inside the Songs folder
          #find "SongsMalalam" -type f -name "*.html" | while read -r file; do
            #sed -i "s/<!-- LAST_UPDATED: {TIMESTAMP} -->/<!-- LAST_UPDATED: $current_datetime -->/" "$file"
          #done

          #find "SongsEnglish" -type f -name "*.html" | while read -r file; do
            #sed -i "s/<!-- LAST_UPDATED: {TIMESTAMP} -->/<!-- LAST_UPDATED: $current_datetime -->/" "$file"
          #done

      # Step 3: Commit and push changes (if any)
      - name: Commit and push changes
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "github-actions@users.noreply.github.com"
          git add e-index.html 
          git commit -m "Update last updated timestamp in e-index.html and Songs folder"
          git push