name: Update Last Updated Timestamp

on:
  push:
    branches:
      - FirstRelease  # Trigger on push to the main branch
  pull_request:
    branches:
      - FirstRelease  # Trigger on pull request to the main branch

jobs:
  update-last-updated:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Update the "Last Updated" placeholder
      - name: Update Last Updated Timestamp
        run: |
          # Get the current date and time
          current_datetime=$(date '+%B %d, %Y, %I:%M %p')

          # List of specific files to update
          files=(
            "../e-index.html"
            "path/to/file2.html"
            "path/to/file3.html"
          )

          # Loop through each file and update the placeholder
          for file in "${files[@]}"; do
            sed -i "s/<!-- LAST_UPDATED: {TIMESTAMP} -->/<!-- LAST_UPDATED: $current_datetime -->/" "$file"
          done


      # Step 3: Commit and push changes (if any)
      - name: Commit and push changes
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "github-actions@users.noreply.github.com"
          git add path/to/your/index.html
          git commit -m "Update last updated timestamp"
          git push
